project:
  type: website
  output-dir: ../docs 

website:
  title: "Social Networks "
#  navbar:
#    left:
#      - href: index.qmd
#        text: Home
#      - about.qmd

format:
  html:
    theme: cosmo
    css: syllabus.css
    toc: true
    output-file: "2025fa_demog280.html"
editor: source

