name: Deploy to Main Website
on:
  push:
    branches: [main]
env:
  COURSE_DIR: "2025fa_demog280"  # Change this to control the subdirectory name
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout class repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install TinyTeX
        run: |
          quarto install tinytex
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: demog280-syllabus
      
      - name: Render Quarto site
        run: |
          cd demog280-syllabus
          quarto render
      
      - name: Deploy to main website
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Clone your website repo with authentication
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/dfeehan/dfeehan.github.io.git website
          cd website
          git checkout master
          
          # Create teaching subdirectories using environment variable
          mkdir -p docs/teaching/${{ env.COURSE_DIR }}
          mkdir -p teaching/${{ env.COURSE_DIR }}
          
          # Copy the rendered syllabus files to both locations
          cp ../docs/*.html docs/teaching/${{ env.COURSE_DIR }}/
          cp ../docs/*.css docs/teaching/${{ env.COURSE_DIR }}/ 2>/dev/null || true
          cp ../docs/*.json docs/teaching/${{ env.COURSE_DIR }}/ 2>/dev/null || true
          cp -r ../docs/site_libs docs/teaching/${{ env.COURSE_DIR }}/ 2>/dev/null || true
          
          cp ../docs/*.html teaching/${{ env.COURSE_DIR }}/
          cp ../docs/*.css teaching/${{ env.COURSE_DIR }}/ 2>/dev/null || true
          cp ../docs/*.json teaching/${{ env.COURSE_DIR }}/ 2>/dev/null || true
          cp -r ../docs/site_libs teaching/${{ env.COURSE_DIR }}/ 2>/dev/null || true
          
          # Commit and push changes to both directories
          git add docs/teaching/ teaching/
          git commit -m "Update syllabus for ${{ env.COURSE_DIR }}" || exit 0
          git push
