name: Deploy to Main Website
on:
  push:
    branches: [main]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout class repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
        
      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: syllabus
        
      - name: Render Quarto site
        run: |
          cd syllabus
          quarto render

      - name: Deploy to main website
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check what files exist
          echo "Contents of current directory:"
          ls -la
          echo "Contents of syllabus directory:"
          ls -la syllabus/
          echo "Contents of syllabus/_site directory:"
          ls -la syllabus/_site/
          
          # Clone your website repo
          git clone https://github.com/dfeehan/dfeehan.github.io.git website
          cd website
          git checkout master
          
          # Create teaching directory if it doesn't exist
          mkdir -p docs/teaching
          
          # Copy the rendered syllabus files (using absolute path from repo root)
          cp -r ../syllabus/_site/* docs/teaching/
          
          # Commit and push changes
          git add docs/teaching/
          git commit -m "Update syllabus from class repo" || exit 0
          git push
